# Generated by Django 5.0.1 on 2024-01-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
